Create airspace.md
websterzh/vatprc-wiki pull request #14
Opened 2022-04-24 03:08 UTC by AkiChen891

新增文件

2022-04-24 10:43 UTC, AkiChen891 commented
Almost Complete

2022-04-25 13:43 UTC, djnken requested changes

2022-04-25 13:43 UTC, djnken commented on airspace.md
> +这里需要注意的是，首次与进近管制员联系时需要报告当前高度、当前位置和接收到的通波编号。很多机组没有报告通波编号的习惯，虽然我们并不强制机组在首次联系进近时必须报告通波编号，但我们扔鼓励机组主动报告。
扔 -> 仍

2022-04-25 16:47 UTC, henrylzy commented on proc-airspace.md
> +
```suggestion
*注意：管制员给出的时间均为真实中的时间，请机组注意将模拟器时间设定为真实时间。如果模拟器时间与真实时间不同步，机组需要手动推算出到达每个位置的真实时间。*

```
对时间做出一些补充

2022-04-25 17:05 UTC, henrylzy commented on proc-airspace.md
> +  > *”西部6415，下到24，可以VOR/DEM进近跑道26号，五边对正报/084径向线入航报。“*
```suggestion
  > *”西部6415，下到24，可以VOR/DME进近跑道26号，五边对正报/084径向线入航报。“*
```
DEM -> DME

2022-04-25 17:08 UTC, AkiChen891 reviewed
已经修改

2022-04-25 17:09 UTC, AkiChen891 reviewed
已修改管制空域章节内的部分错误

2022-04-26 10:03 UTC, LeoChen98 requested changes
没什么问题，有一些细节需要再看一下。

2022-04-26 10:03 UTC, LeoChen98 commented on proc-airspace.md
> +  初次联系程序塔台时，塔台会以语音的方式向机组播报地面天气信息和进场信息。机组应当完整复述以上内容，确认复述正确后，塔台管制员会让机组回到区调频率。
建议与前面相同/相似内容合并简化。

2022-04-26 11:54 UTC, AkiChen891 reviewed
已修改

2022-04-26 12:01 UTC, AkiChen891 reviewed
已修改

2022-04-26 16:09 UTC, LeoChen98 commented on airspace.md
> +***提示：请注意申请放行的时机，不要过早的申请放行。我们推荐航空器在准备完毕后再申请放行。“准备完毕”意味着飞行机组确保：a.航空器舱门锁闭； b.航空器已完全做好开车准备。c.航空器牵引车已经连接上了航空器（自滑机位除外）***
> CAAC确实是这么写的...大概是现实里头申请放行完了之后马上就可以申请推开？

但是实际上都是要完准备推才挂拖车，拖车分分钟还姗姗来迟(x

2022-04-27 06:45 UTC, djnken commented
> 已修改

现实里面是复诵PDC，完事就可以申请推出

2022-04-29 10:34 UTC, henrylzy commented on airspace.md
> +注意，以下所有教程中的样例均默认在VATPRC所管辖的空域内发生。当您在国外进行连线飞行时，所执行的标准程序和陆空对话规范等都可能会有很大的不同，具体视对应分部的规章制度而定。
```suggestion
注意，以下所有教程中的样例均默认在VATPRC所管辖的空域内发生。当您在其他地方进行连线飞行时，所执行的标准程序和陆空对话规范等都可能会有很大的不同，具体视对应分部的规章制度而定。
```
国外->其他地方

2022-04-29 10:37 UTC, henrylzy commented on airspace.md
> +此外，VATPRC目前暂时代管蒙古国的ZMUB Ulaanbaatar 乌兰巴托情报区。有关乌兰巴托情报区的内容，参见*乌兰巴托飞行情报区*
```suggestion
此外，VATPRC目前暂时代管蒙古国的ZMUB Ulaanbaatar 乌兰巴托情报区。有关乌兰巴托情报区的内容，参见*[乌兰巴托飞行情报区](./ZMUB.md)*
```
添加链接

2022-04-29 20:14 UTC, 787dreamliner-9 commented on airspace.md
> +有些时候，管制员不会给出推开的朝向，这意味着机组可以自行决定推开的方向，一般的参考方向是机头朝向起飞跑道位置。
```suggestion
有些时候，管制员不会给出推开的朝向，这意味着机组可以自行决定推开的方向，一般的参考方向是机头朝向起飞跑道位置。但仍建议机组查阅机场AD的 `3.7 航空器进出停机位的滑行限制` 章节，例如北京大兴机场部分后推程序，以免与其他机组产生不必要的冲突。
```

2022-04-29 20:14 UTC, 787dreamliner-9 commented on airspace.md
> +  由于某些原因，机组可能会遇到语音呼叫但频率无人应答的情况，这通常是网络环境较差或是AFV模拟真实无线电限制的原因。当无人应答时，请尝试用文字的方式联系管制员。如果语音和文字都联系不到管制员，请先返回上一频率确认频率是否正确，如果频率正确，但仍无法在正确的频率通过语音或文字联系到管制员，可通过.wallop指令联系在线的SUP寻求帮助。
```suggestion
  由于某些原因，机组可能会遇到语音呼叫但频率无人应答的情况，这通常是网络环境较差或是AFV模拟真实无线电限制的原因。当无人应答时，请尝试用文字的方式联系管制员。如果语音和文字都无法联系到管制员，请先返回上一频率确认频率是否正确，如果频率正确，但仍无法通过语音或文字与管制员建立联系，可通过.wallop指令联系在线的SUP寻求帮助。
```

2022-04-29 20:15 UTC, 787dreamliner-9 commented on airspace.md
> +有些时候，管制员不会给出推开的朝向，这意味着机组可以自行决定推开的方向，一般的参考方向是机头朝向起飞跑道位置。
好像我这话有语病，你再看看

2022-04-30 11:52 UTC, henrylzy commented
根据VATSIM Global Rating Policy所规定，VATSIM管制员的级别遵循“渐进式”(Graduated)的原则，即每个管制员必须按放行->地面->塔台->进近（离场）->区域的顺序进行培训和考核，这样做可以保证每个实施“向下兼容”的管制员，都具备了在被兼容席位提供管制服务的要求。在这个前提下，我们可以将所有管制席位按照等级由高到低进行排序，如下表：

| 席位名称 | 席位后缀 | 最低管制员等级（最低管制学员等级） | 管辖范围 |
| --- | --- | --- | --- |
| 区域席 | `_CTR` | C1（S3） | 该区域空域内所有进近管制区以外的空域 |
| 进近（离场）席 / 程序塔台<sup>1</sup> | `_APP`(`_DEP`) / `_TWR`<sup>1</sup> | S3（S2） | 该进近管制区内所有塔台管制区以外的空域 / 程序塔台管制区的空域以及该机场所有跑道的运行 |
| 塔台席 | `_TWR` | S2（S1） | 所在机场所有跑道的运行 |
| 地面席 | `_GND` | S2（S1） | 所在机场所有滑行道的运行 |
| 放行席 | `_DEL` | S2（S1） | 所在机场放行许可的发布 |

<sup>1</sup> *有关程序塔台的介绍见“[特殊空域内的飞行](./proc-airspace.md)”。下文中所提到的塔台席，除被特别注明为程序塔台的以外，均表示非程序塔台（即使用雷达或ADS-B对机场附近空域实施监控的塔台，管辖范围为该机场的所有跑道）。*

---
根据上表，当`低等级席位`不在线时，`高等级席位`应当在条件允许的情况下，“向下兼容”空域内所有空缺的`低等级席位`（如`区域`应“向下兼容”空域内所有不在线的席位，`塔台`管制员应向下兼容所在机场的`地面`和`放行`席位）。

在实施“向下兼容”时，遵循等级由低到高的“就近原则”进行兼容。也就是说，当`塔台`和`区域`同时在线时，空缺的`放行`和`地面`席位应被与它们**等级最接近**的`塔台`兼容，而`区域`仅兼容该机场所在的进近空域，以及其空域内的其他空缺席位。

- 当`塔台管制员`实施“向下兼容”时，应遵循“就近原则”，且仅可以兼容**所在机场**的`低等级空缺`席位，如：该机场的`地面席`和`放行席`。
- 当`进近管制员`实施“向下兼容”时，应遵循“就近原则”，对其空域内所有机场的空缺席位进行兼容。
- 当`区域管制员`实施“向下兼容”时，应遵循“就近原则”，对其空域内所有`进近管制区`和`程序塔台管制区`进行兼容。

注意：
- “向下兼容”的实施与否取决于高等级席位的工作量是否允许这样做。当高等级席位认为其原本管辖范围内的工作量较大时，可能会放弃对部分席位的兼容。无论如何，机组应首先联系相应管制员，并与管制员确认是否应当听其指挥。
- 由于部分进近管制区涵盖多个机场，机组应查看航图确认应当联系的进近管制员。机组无法确定是否在其空域内时，应主动联系该管制员并向其询问。
- 当所在空域有管制员在线时（PRC_FSS除外，除非在线的PRC_FSS管制员在其ATC Info中特别注明了“向下兼容”该机场），所有飞行（仪表或目视）都应向管制员申请放行许可。在不确定时，请与在线管制员确认其管辖范围。

2022-04-30 12:08 UTC, AkiChen891 reviewed
已修改

2022-05-02 05:57 UTC, LeoChen98 requested changes
建议修改错别字和逻辑错误（已标出），并为程序管制的陆空通话部分加入英文对话版本。

2022-05-02 05:57 UTC, LeoChen98 commented on airspace.md
> +  **请注意，“雷达服务终止”不意味着“管制服务结束”，尤其当机组正在接受区域管制员的Top-down Service时。“雷达服务终止”仅代表当前席位不再为机组提供雷达管制服务，机组可能进入了ADS-B管制空域或是无雷达的塔台管制空域。有管雷达管制，参见程序管制章节**
```suggestion
  **请注意，“雷达服务终止”不意味着“管制服务结束”，尤其当机组正在接受区域管制员的Top-down Service时。“雷达服务终止”仅代表当前席位不再为机组提供雷达管制服务，机组可能进入了ADS-B管制空域或是无雷达的塔台管制空域。有关程序管制，参见程序管制章节**
```

捉虫： `有管` -> `有关`
逻辑错误： `雷达管制` -> `程序管制`

2022-05-02 10:47 UTC, AkiChen891 reviewed
根据PR修改部分内容

2022-05-03 08:14 UTC, henrylzy commented on airspace.md
> +
```suggestion
---
对于不同情况下指令中的“识别”的解释：
1. 雷达“识别”（信息通报）
  “雷达识别”代表管制员通过雷达监测出的航空器位置和/或其应答机编码与其标牌信息（包括呼号、飞行计划等）相关联的动作。
  当管制员向机组通报“雷达识别”时，表示管制员已经完成了上述动作。这时机组应当回复其呼号表示收到。
  
2. 应答机“识别”（指令）
  “应答机识别”代表管制员要求机组使用其应答机进行位置识别的指令。机组应当按下其应答机面板中的 `Ident` 按钮。此时机组航空器的应答机将会发送一个特殊位置识别（SPI: Special Position Identification）信号。当地面二次雷达接收到这个信号时，将会在管制员的雷达上将此航空器高亮或突出显示，以便于管制员在多个航空器中快速准确的发现该航空器的位置。
```
添加了关于识别的解释

2022-05-03 09:04 UTC, AkiChen891 reviewed
修改部分内容

2022-05-03 14:32 UTC, RudiZhang commented on airspace.md
> +PRC_FSS是一个经VATSIM批准的飞行服务站，呼号为“北京飞服(Beijing Control)”。PRC_FSS的水平范围覆盖北京、沈阳、上海、广州、武汉、昆明、兰州、乌鲁木齐、三亚共计9个情报区。
北京飞服不覆盖武汉情报区

2022-05-06 07:41 UTC, djnken requested changes

2022-05-06 07:41 UTC, djnken commented on airspace.md
> ++ **机组不确定该联系哪个管制席位。** 此时机组应当直接在频率中询问或是私信管制员。
“此时机组应当通过可能隶属管制的席位频率，或私信相应的管制员询问”

2022-05-06 07:41 UTC, djnken commented on airspace.md
> +很多管制员反映机组在首次联系时很少查看ATC info,造成了不必要的频率占用。事实上ATC info是很重要的信息，它告诉了机组联系该管制席位的一些注意事项。举一个最简单的例子，经常有机组把ZSSS_APP叫成虹桥进近，把ZGJD_APP叫成深圳进近。然而实际上这些席位的管制员在上线时都在其ATC info中明确的写出了他们的呼号该怎么念，但是很多机组并没有看ATC info的习惯。
可以补充atc info可能包含所管制的机场？虽然下面举例中已有提及

2022-05-06 07:41 UTC, djnken commented on airspace.md
> +> ATC: *"Air China 4115, readback is correct, contact next frequency, goodday"*
不会直接说“下一个频率”吧 应该还是会给一个频率 或者要求守听本频率

2022-05-06 07:41 UTC, djnken commented on airspace.md
> +  > 管制：*“国航4115，由于间隔，减马赫数到点78”*
跟上文统一一下 用.78或者点78

2022-05-06 07:41 UTC, djnken commented on airspace.md
> ++ 偏置。根据间隔需要，区域管制员会给出偏置的指令。通俗的讲，偏置就是讲航路向左或向右平移几海里。
补充：部分机模支持执行此类动作，如果您不理解如何执行或者机模无法执行，请告知管制员。

2022-05-06 07:41 UTC, djnken commented on airspace.md
> +> *“国航4115， 准备好下高报”*
解释一下什么是准备好

2022-05-06 07:41 UTC, djnken commented on airspace.md
> +> *"Air China 4115, runway 01 localizar established/fully established."*
ILS fully established

2022-05-06 07:41 UTC, djnken commented on airspace.md
> +  由于某些原因，机组可能会遇到语音呼叫但频率无人应答的情况，这通常是网络环境较差或是AFV模拟真实无线电限制的原因。当无人应答时，请尝试用文字的方式联系管制员。如果语音和文字都无法联系到管制员，请先返回上一频率确认频率是否正确，如果频率正确，但仍无法通过语音或文字与管制员建立联系，可通过.wallop指令联系在线的SUP寻求帮助。
补充：请注意，与SUP联系时需要使用英语联系，绝大多数的SUP只可以使用英文对话

2022-05-09 06:29 UTC, paul891014 approved these changes

2022-05-20 10:53 UTC, LeoChen98 approved these changes
请针对现有意见进行修改，当前版本未发现其他重大错漏，同意合并。

2022-05-20 10:53 UTC, LeoChen98 commented on airspace.md
> +此外，VATPRC目前暂时代管蒙古国的ZMUB Ulaanbaatar 乌兰巴托情报区。有关乌兰巴托情报区的内容，参见*[乌兰巴托飞行情报区](./ZMUB.md)*
```suggestion
此外，VATPRC目前暂时代管蒙古国的ZMUB Ulaanbaatar 乌兰巴托情报区。有关乌兰巴托情报区的内容，参见[乌兰巴托飞行情报区](./ZMUB.md)
```

链接文本加粗无效，建议删除加粗

2022-05-20 10:53 UTC, LeoChen98 commented on airspace.md
> +#### 待补充
```suggestion

```

对于最终发布版本，请删除该行

2022-05-20 12:45 UTC, merged