Code of conduct
websterzh/vatprc-wiki pull request #16
Opened 2022-04-24 07:44 UTC by henrylzy

2022-04-24 10:51 UTC, CaptainYukinoshitaHachiman commented on COC_translate_full.md
> +A9 - 除本行为准则第B3(b)条所规定的情况外，会员不得在连线期间离开电脑。没有积极参与网络活动的会员（如以观察员身份连线的会员）不得长时间登录VATSIM网络。
“长时间“改成”过长时间“是否会更合适？

2022-04-24 10:52 UTC, CaptainYukinoshitaHachiman commented on COC_translate_full.md
> +A11 - 会员不可以在任何VATSIM所使用的软件、论坛、新闻组、社交媒体或电子邮件名单，以及VATSIM所认可的地区、分部及其分支机构对他人进行威胁、骚扰、跟踪、或以其他方式侵犯他人的合法权益（包括但不限于其隐私权和公开权）。这包括以威胁、骚扰、跟踪或以其他方式侵犯他人合法权益为目的，使用上述资源寻找、定位或以其他方式发现会员的联系方法。此外，会员不得发表、张贴、分发、散布或者使用任何类型的
“mailing list”一般在中文中被称为“邮件列表”

2022-04-24 10:56 UTC, CaptainYukinoshitaHachiman commented on COC_translate_full.md
> +A14 - 语音是VATSIM首选的通讯方式，但仅使用文字进行通讯的会员也应受到与其他会员相同水平的服务。我们不会限制或打压某一种通讯方式，但只可以传输未被二次加工的语音。
“我们不会限制或打压”按照英文原文的措辞翻译成“限制或打压...的规则不应存在/被制定”是否会更合适？

2022-04-24 11:01 UTC, henrylzy commented on COC_translate_full.md
> +A14 - 语音是VATSIM首选的通讯方式，但仅使用文字进行通讯的会员也应受到与其他会员相同水平的服务。我们不会限制或打压某一种通讯方式，但只可以传输未被二次加工的语音。
不应存在或被指定写出来显得比较生硬，且主语不好定义

2022-04-24 11:05 UTC, CaptainYukinoshitaHachiman commented on COC_translate_full.md
> +(b) 如果会员在其飞行计划中，或其他VATSIM运行的媒体上发布了其连线过程的直播/录像的链接，则该直播/录像的整体以及其非正式媒介（包括聊天、弹幕、评论等）都受到本行为规范的管辖。
"VATSIM运行的"改为“由VATSIM运行的”可能会更通顺些？

2022-04-24 11:06 UTC, henrylzy commented on COC_translate_full.md
> +(b) 如果会员在其飞行计划中，或其他VATSIM运行的媒体上发布了其连线过程的直播/录像的链接，则该直播/录像的整体以及其非正式媒介（包括聊天、弹幕、评论等）都受到本行为规范的管辖。
可

2022-04-24 11:07 UTC, henrylzy commented on COC_translate_full.md
> +A11 - 会员不可以在任何VATSIM所使用的软件、论坛、新闻组、社交媒体或电子邮件名单，以及VATSIM所认可的地区、分部及其分支机构对他人进行威胁、骚扰、跟踪、或以其他方式侵犯他人的合法权益（包括但不限于其隐私权和公开权）。这包括以威胁、骚扰、跟踪或以其他方式侵犯他人合法权益为目的，使用上述资源寻找、定位或以其他方式发现会员的联系方法。此外，会员不得发表、张贴、分发、散布或者使用任何类型的
可

2022-04-24 11:07 UTC, CaptainYukinoshitaHachiman commented on COC_translate_full.md
> +B2 - 除非管制员明确同意以外，飞行员不得在连线过程中将其模拟器暂停。当管制员要求时，飞行员应当立刻终止其模拟器的暂停状态。
将“when operating under air traffic control”明确译出是否会更符合原意/不易被误解？

2022-04-24 11:07 UTC, henrylzy commented on COC_translate_full.md
> +A9 - 除本行为准则第B3(b)条所规定的情况外，会员不得在连线期间离开电脑。没有积极参与网络活动的会员（如以观察员身份连线的会员）不得长时间登录VATSIM网络。
可

2022-04-24 11:09 UTC, CaptainYukinoshitaHachiman commented on COC_translate_full.md
> +B3(b) - 当飞行员在飞行中遇到必须要离开电脑前的情况，我们鼓励飞行员断开与VATSIM的连接。即便本守则有与之相悖的规定，无人看管的飞行员连接最多不可以超过30分钟。
保持原文的被动用法译成“成员被鼓励”，或者将主语改成“本守则”而非“我们”是否会更恰当？

2022-04-24 11:11 UTC, CaptainYukinoshitaHachiman commented on COC_translate_full.md
> +B5 - 飞行员在无管制空域内飞行时应当时刻守听122.800MHz或其他被指定为UNICOM的频率，直到其进入管制空域内。飞行员应当在指定的UNICOM频率中报告其意图以避免冲突，同时方便其他飞行员。
“Where another pilot may benefit,”翻译成“当其他飞行员有可能从中受益时”是否会更符合原文含义？

2022-04-24 11:12 UTC, CaptainYukinoshitaHachiman commented on COC_translate_full.md
> +A14 - 语音是VATSIM首选的通讯方式，但仅使用文字进行通讯的会员也应受到与其他会员相同水平的服务。我们不会限制或打压某一种通讯方式，但只可以传输未被二次加工的语音。
> 不应存在或被指定写出来显得比较生硬，且主语不好定义

要不把主语换成“本准则”

2022-04-24 11:14 UTC, CaptainYukinoshitaHachiman commented on COC_translate_full.md
> +A14 - 语音是VATSIM首选的通讯方式，但仅使用文字进行通讯的会员也应受到与其他会员相同水平的服务。我们不会限制或打压某一种通讯方式，但只可以传输未被二次加工的语音。
“本准则不允许限制或打压某一种通讯方式，但成员只可以传输未被二次加工的语音。” @henrylzy

2022-04-24 11:17 UTC, CaptainYukinoshitaHachiman commented on COC_translate_full.md
> +B6 - 任何飞行活动都不可以声明自己优先于其他机组。我们仅允许飞行员在管制空域内宣告紧急情况。不论出于任何原因，管制员有权要求飞行员终止其紧急情况。此时飞行员应立刻中止其对于紧急情况的模拟，或断开与VATSIM的连接。飞行员在任何情况下都不得模拟任何非法的行为，包括但不限于以任何方式（如将应答机调至7500）宣告劫机/被劫机。
将主语改成“本守则”而非“我们”是否会更恰当？

2022-04-24 11:19 UTC, CaptainYukinoshitaHachiman commented on COC_translate_full.md
> +B9 - 飞行员在使用模拟器的倍速功能时必须时刻监控其飞行，以确保不会干扰到其他会员。在管制空域内时，飞行员使用倍速功能前必须得到管制员的许可，并且在管制员要求时，立即退出倍速模式。
"express permission"译成“**明确**许可”是否更贴切原文？

2022-04-24 11:19 UTC, henrylzy commented on COC_translate_full.md
> +B3(b) - 当飞行员在飞行中遇到必须要离开电脑前的情况，我们鼓励飞行员断开与VATSIM的连接。即便本守则有与之相悖的规定，无人看管的飞行员连接最多不可以超过30分钟。
鼓励更多应该是从运行层面上讲而不是规章制度的层面，所以如果主语改为本守则鼓励感觉有些奇怪。被动太多感觉很生硬

2022-04-24 11:20 UTC, henrylzy commented on COC_translate_full.md
> +B5 - 飞行员在无管制空域内飞行时应当时刻守听122.800MHz或其他被指定为UNICOM的频率，直到其进入管制空域内。飞行员应当在指定的UNICOM频率中报告其意图以避免冲突，同时方便其他飞行员。
这句话我一直觉得不太通顺，改成当其他飞行员有可能从中受益时稍好一些，但是还是有些奇怪

2022-04-24 11:21 UTC, henrylzy commented on COC_translate_full.md
> +B6 - 任何飞行活动都不可以声明自己优先于其他机组。我们仅允许飞行员在管制空域内宣告紧急情况。不论出于任何原因，管制员有权要求飞行员终止其紧急情况。此时飞行员应立刻中止其对于紧急情况的模拟，或断开与VATSIM的连接。飞行员在任何情况下都不得模拟任何非法的行为，包括但不限于以任何方式（如将应答机调至7500）宣告劫机/被劫机。
这样，改成飞行员仅可以.....，去xxx的主语

2022-04-24 11:21 UTC, henrylzy commented on COC_translate_full.md
> +B9 - 飞行员在使用模拟器的倍速功能时必须时刻监控其飞行，以确保不会干扰到其他会员。在管制空域内时，飞行员使用倍速功能前必须得到管制员的许可，并且在管制员要求时，立即退出倍速模式。
可

2022-04-24 11:22 UTC, henrylzy commented on COC_translate_full.md
> +B2 - 除非管制员明确同意以外，飞行员不得在连线过程中将其模拟器暂停。当管制员要求时，飞行员应当立刻终止其模拟器的暂停状态。
根据SUP的实际案例来看，不论是否在管制空域内都禁止暂停，所以，这个待定

2022-04-24 11:25 UTC, CaptainYukinoshitaHachiman commented on COC_translate_full.md
> +后记 - VATSIM的主要目标是提供一个有教育意义，同时模拟真实飞行和管制环境，以及一个所有人都可以在此体验到他们的爱好所带来的快乐的平台。通过遵守本行为准则中所规定的简单规则，可以确保每个人都能学习并且结交来自世界各地的新朋友。在此，欢迎我们的各位新会员，也希望大家可以享受这个平台所带来的乐趣。
在第一句话中，“一个”出现了两次，应考虑将第二个删除，因为“有教育意义，同时模拟真实飞行和管制环境，以及所有人都可以在此体验到他们的爱好所带来的快乐的”作长定语。另外，可考虑按照原文措辞，将“and, most importantly, to”翻译成“并且（，）最重要的，所有人都可以......”以保留原文的强调。

2022-04-24 11:26 UTC, CaptainYukinoshitaHachiman commented on COC_translate_full.md
> +后记 - VATSIM的主要目标是提供一个有教育意义，同时模拟真实飞行和管制环境，以及一个所有人都可以在此体验到他们的爱好所带来的快乐的平台。通过遵守本行为准则中所规定的简单规则，可以确保每个人都能学习并且结交来自世界各地的新朋友。在此，欢迎我们的各位新会员，也希望大家可以享受这个平台所带来的乐趣。
第二句话中“可以确保每个人”主语不明确

2022-04-24 11:27 UTC, henrylzy commented on COC_translate_full.md
> +后记 - VATSIM的主要目标是提供一个有教育意义，同时模拟真实飞行和管制环境，以及一个所有人都可以在此体验到他们的爱好所带来的快乐的平台。通过遵守本行为准则中所规定的简单规则，可以确保每个人都能学习并且结交来自世界各地的新朋友。在此，欢迎我们的各位新会员，也希望大家可以享受这个平台所带来的乐趣。
可

2022-04-24 11:28 UTC, CaptainYukinoshitaHachiman commented on COC_translate_full.md
> +B5 - 飞行员在无管制空域内飞行时应当时刻守听122.800MHz或其他被指定为UNICOM的频率，直到其进入管制空域内。飞行员应当在指定的UNICOM频率中报告其意图以避免冲突，同时方便其他飞行员。
> 这句话我一直觉得不太通顺，改成当其他飞行员有可能从中受益时稍好一些，但是还是有些奇怪

主要是按照现在的译法含义应该与原文有出入吧？ @henrylzy

2022-04-24 11:29 UTC, henrylzy commented on COC_translate_full.md
> +后记 - VATSIM的主要目标是提供一个有教育意义，同时模拟真实飞行和管制环境，以及一个所有人都可以在此体验到他们的爱好所带来的快乐的平台。通过遵守本行为准则中所规定的简单规则，可以确保每个人都能学习并且结交来自世界各地的新朋友。在此，欢迎我们的各位新会员，也希望大家可以享受这个平台所带来的乐趣。
> 第二句话中“可以确保每个人”主语不明确

建议？

2022-04-24 11:34 UTC, CaptainYukinoshitaHachiman commented on COC_translate_full.md
> +后记 - VATSIM的主要目标是提供一个有教育意义，同时模拟真实飞行和管制环境，以及一个所有人都可以在此体验到他们的爱好所带来的快乐的平台。通过遵守本行为准则中所规定的简单规则，可以确保每个人都能学习并且结交来自世界各地的新朋友。在此，欢迎我们的各位新会员，也希望大家可以享受这个平台所带来的乐趣。
> > 第二句话中“可以确保每个人”主语不明确
> 
> 建议？

直接译成“每个人都将能够“，不将”ensure”显式的体现出来如何？

2022-04-24 11:35 UTC, henrylzy commented on COC_translate_full.md
> +B5 - 飞行员在无管制空域内飞行时应当时刻守听122.800MHz或其他被指定为UNICOM的频率，直到其进入管制空域内。飞行员应当在指定的UNICOM频率中报告其意图以避免冲突，同时方便其他飞行员。
> > 这句话我一直觉得不太通顺，改成当其他飞行员有可能从中受益时稍好一些，但是还是有些奇怪
> 
> 主要是按照现在的译法含义应该与原文有出入吧？ @henrylzy

但是原文的意思没有当，而是这个行为可能会让其他人收益

2022-04-24 11:39 UTC, CaptainYukinoshitaHachiman commented on COC_translate_full.md
> +后记 - VATSIM的主要目标是提供一个有教育意义，同时模拟真实飞行和管制环境，并且，最重要的是所有人都可以在此体验到他们的爱好所带来的快乐的平台。通过遵守本行为准则中所规定的简单规则，可以确保每个人都能学习并且结交来自世界各地的新朋友。在此，欢迎我们的各位新会员，也希望大家可以享受这个平台所带来的乐趣。
```suggestion
后记 - VATSIM的主要目标是提供一个有教育意义，同时模拟真实飞行和管制环境，并且最重要的，所有人都可以在此体验到他们的爱好所带来的快乐的平台。通过遵守本行为准则中所规定的简单规则，可以确保每个人都能学习并且结交来自世界各地的新朋友。在此，欢迎我们的各位新会员，也希望大家可以享受这个平台所带来的乐趣。
```

现有译法中第一句话有“目标是”与“最重要的是”两个谓语。不过经上述修改后还将会比较拗口，可考虑将此句在保留原文含义的情况下拆分成多句以方便阅读理解/避免歧义？

2022-04-24 11:51 UTC, LeoChen98 commented on COC_translate_full.md
> +后记 - VATSIM的主要目标是提供一个有教育意义，同时模拟真实飞行和管制环境，并且，最重要的是所有人都可以在此体验到他们的爱好所带来的快乐的平台。通过遵守本行为准则中所规定的简单规则，可以确保每个人都能学习并且结交来自世界各地的新朋友。在此，欢迎我们的各位新会员，也希望大家可以享受这个平台所带来的乐趣。
后记 - VATSIM的主要目标是提供一个有教育意义，同时模拟真实飞行和管制环境**的平台，最重要的是，我们希望所有人都可以在这里体验到爱好所带来的的快乐**。通过遵守本行为准则中所规定的简单规则，可以确保每个人都能学习并且结交来自世界各地的新朋友。在此，欢迎我们的各位新会员，也希望大家可以享受这个平台所带来的乐趣。

2022-04-24 11:51 UTC, CaptainYukinoshitaHachiman commented on COC_translate_full.md
> +B5 - 飞行员在无管制空域内飞行时应当时刻守听122.800MHz或其他被指定为UNICOM的频率，直到其进入管制空域内。飞行员应当在指定的UNICOM频率中报告其意图以避免冲突，同时方便其他飞行员。
> > > 这句话我一直觉得不太通顺，改成当其他飞行员有可能从中受益时稍好一些，但是还是有些奇怪
> > 
> > 
> > 主要是按照现在的译法含义应该与原文有出入吧？ @henrylzy
> 
> 但是原文的意思没有当，而是这个行为可能会让其他人受益

@henrylzy where在这里应该是when的意思吧，还是我理解错了？

2022-04-24 11:52 UTC, CaptainYukinoshitaHachiman commented on COC_translate_full.md
> +B3(b) - 当飞行员在飞行中遇到必须要离开电脑前的情况，我们鼓励飞行员断开与VATSIM的连接。即便本守则有与之相悖的规定，无人看管的飞行员连接最多不可以超过30分钟。
> 鼓励更多应该是从运行层面上讲而不是规章制度的层面，所以如果主语改为本守则鼓励感觉有些奇怪。被动太多感觉很生硬

使用“我们”的话就会出现一个问题：“我们”指谁。当然不细究的话问题不大）

2022-04-24 12:00 UTC, CaptainYukinoshitaHachiman commented on COC_translate_full.md
> +后记 - VATSIM的主要目标是提供一个有教育意义，同时模拟真实飞行和管制环境，并且，最重要的是所有人都可以在此体验到他们的爱好所带来的快乐的平台。通过遵守本行为准则中所规定的简单规则，可以确保每个人都能学习并且结交来自世界各地的新朋友。在此，欢迎我们的各位新会员，也希望大家可以享受这个平台所带来的乐趣。
> 建议如上修改

“...的平台，最重要的是...”中将逗号改为句号或分号如何

2022-04-24 12:24 UTC, LeoChen98 reviewed
已遍阅全文，私认为总体翻译恰当无误，浅提建议如下：
1. 按照实际排版需求为子项列表加入适当的缩进，或使用markdown语法中提供的自动列表，以提高多子项时列表的易读性。
2. 修正引号的使用，中文文本中通常不单独使用单引号（`‘’`）。
3. 补全超链接，使文档中链接可以跳转到相关页面。
4. 罗列参数的条目建议使用表格以提高易读性，例如C8的视程配备表。
5. 建议调整后记的措辞。

以上为本人拙见，望能抛砖引玉。

2022-04-24 12:24 UTC, LeoChen98 commented on COC_translate_full.md
> +C5 - 管制席位遵循’先到先得‘原则。经所属分部批准后，相关地区可以引入席位预定机制，允许管制员预约或计划于某一特定的（合理）时间段内在其指定席位提供管制服务。此外，当一位管制员与服务器的连接由于网络或其他因素而被中断，并在合理的时间范围内重新登陆时，另一名管制员已经登录了相同席位的情况下，后者应当将此席位归还至前者。
```suggestion
C5 - 管制席位遵循“先到先得”原则。经所属分部批准后，相关地区可以引入席位预定机制，允许管制员预约或计划于某一特定的（合理）时间段内在其指定席位提供管制服务。此外，当一位管制员与服务器的连接由于网络或其他因素而被中断，并在合理的时间范围内重新登陆时，另一名管制员已经登录了相同席位的情况下，后者应当将此席位归还至前者。
```

建议修改标点符号

2022-04-24 12:24 UTC, LeoChen98 commented on COC_translate_full.md
> +C2 - 管制员应当遵守地方性的规则以及程序。选择在其所属或所被分配地区/分部/分支机构以外的地区提供管制服务的管制员，必须遵守该地区的地方性规则及程序，并且需要根据当地要求，申请并取得‘客座管制员’的身份。‘客座管制员’的身份受到Transfer and Visiting Controllers Policy (https://www.vatsim.net/documents/transf .
```suggestion
管制员应当遵守地方性的规则以及程序。选择在其所属或所被分配地区/分部/分支机构以外的地区提供管制服务的管制员，必须遵守该地区的地方性规则及程序，并且需要根据当地要求，申请并取得“客座管制员”的身份。“客座管制员”的身份受到Transfer and Visiting Controllers Policy ([https://www.vatsim.net/documents/transf ... ler-policy](https://www.vatsim.net/documents/transfer-and-visiting-controller-policy)) 的规范。
```

修正标点符号并补全超链接

2022-04-24 12:24 UTC, LeoChen98 commented on COC_translate_full.md
> +C3 - 会员以观察员身份连接到VATSIM网络时，所使用的呼号必须以'_OBS'结尾。下划线前应当使用会员注册名的英文首字母（如：张三应使用SZ_OBS或ZS_OBS）或当地所允许的其他名称。VATSIM允许官方工作人员使用可以表明他们工作人员身份的呼号以观察员的身份连接到网络。观察员在连线时不得以任何形式（文字或/和语音）在公共频道进行通讯或提供管制服务。
```suggestion
C3 - 会员以观察员身份连接到VATSIM网络时，所使用的呼号必须以`_OBS`结尾。下划线前应当使用会员注册名的英文首字母（如：张三应使用SZ_OBS或ZS_OBS）或当地所允许的其他名称。VATSIM允许官方工作人员使用可以表明他们工作人员身份的呼号以观察员的身份连接到网络。观察员在连线时不得以任何形式（文字或/和语音）在公共频道进行通讯或提供管制服务。
```

此处建议使用代码块格式引入深色背景填充

2022-04-24 12:24 UTC, LeoChen98 commented on COC_translate_full.md
> +(1) 会员在注册时所提交的真实的全名，如：Joseph Smith
```suggestion
    (1) 会员在注册时所提交的真实的全名，如：Joseph Smith  
```

建议对列表项进行适当的缩进以增加易读性，下同。

2022-04-24 12:24 UTC, LeoChen98 commented on COC_translate_full.md
> +A7 - 会员仅限使用VATSIM许可的软件连接到VATSIM网络。 (https://www.vatsim.net/documents/approved-software) 会员在连接到VATSIM网络之前需要确保已经了解所使用软件的基本使用方法。
```suggestion
A7 - 会员仅限使用VATSIM许可的软件连接到VATSIM网络。([https://www.vatsim.net/documents/approved-software](https://www.vatsim.net/documents/approved-software))会员在连接到VATSIM网络之前需要确保已经了解所使用软件的基本使用方法。  
```

建议补全超链接

2022-04-24 12:24 UTC, LeoChen98 commented on COC_translate_full.md
> +A13 - 会员不得以观察员、飞行员或管制员以外的身份连接到VATSIM。任何涉及到军事、准军事或文职政府机构的行动和/或活动必须由经VATSIM批准的特别行动组织授权方可进行。特别行动的限制及程序可以在特别行动政策中找到。(https://www.vatsim.net/documents/special-operations-policy)
```suggestion
A13 - 会员不得以观察员、飞行员或管制员以外的身份连接到VATSIM。任何涉及到军事、准军事或文职政府机构的行动和/或活动必须由经VATSIM批准的特别行动组织授权方可进行。特别行动的限制及程序可以在特别行动政策中找到。([https://www.vatsim.net/documents/special-operations-policy](https://www.vatsim.net/documents/special-operations-policy))  
```

补全超链接

2022-04-24 12:24 UTC, LeoChen98 commented on COC_translate_full.md
> +注意：在VATSIM Global Rating Policy(http://www.vatsim.net/documents/global-ratings-policy) 的附件B中定义了所有被VATSIM许可的飞行服务站。
```suggestion
注意：在VATSIM Global Rating Policy([http://www.vatsim.net/documents/global-ratings-policy](http://www.vatsim.net/documents/global-ratings-policy)) 的附件B中定义了所有被VATSIM许可的飞行服务站。
```

补全超链接

2022-04-24 12:24 UTC, LeoChen98 commented on COC_translate_full.md
> +C6 - 管制员仅可以使用被批准的席位及其对应频率提供管制服务。管制员需要按总部及分部政策，在他们被批准/许可的席位提供管制服务。详情见Global Ratings Policy (https://www.vatsim.net/documents/global-ratings-policy)以及Transfer and Visiting Controller Policy (https://ww
```suggestion
C6 - 管制员仅可以使用被批准的席位及其对应频率提供管制服务。管制员需要按总部及分部政策，在他们被批准/许可的席位提供管制服务。详情见Global Ratings Policy ([https://www.vatsim.net/documents/global-ratings-policy](https://www.vatsim.net/documents/global-ratings-policy))以及Transfer and Visiting Controller Policy ([https://www.vatsim.net/documents/transf ... ler-policy](https://www.vatsim.net/documents/transfer-and-visiting-controller-policy))
```

补全超链接

2022-04-24 12:24 UTC, LeoChen98 commented on COC_translate_full.md
> +C7 - 每位管制员仅可以额外建立一个与VATSIM网络的连接用于为一个机场提供语音航行情报通波服务，且该机场必须在真实中存在此服务。此外，通波必须包含一个英文的文字版本。通波需要按照ATC Frequency Management and Information Policy (https://www.vatsim.net/air-traffic-control-frequency-and-i
```suggestion
C7 - 每位管制员仅可以额外建立一个与VATSIM网络的连接用于为一个机场提供语音航行情报通波服务，且该机场必须在真实中存在此服务。此外，通波必须包含一个英文的文字版本。通波需要按照ATC Frequency Management and Information Policy ([https://www.vatsim.net/air-traffic-control-frequency-and-information-management-policy](https://www.vatsim.net/air-traffic-control-frequency-and-information-management-policy))中所要求的格式书写。
```

补全超链接

2022-04-24 12:24 UTC, LeoChen98 commented on COC_translate_full.md
> +后记 - VATSIM的主要目标是提供一个有教育意义，同时模拟真实飞行和管制环境，并且，最重要的是所有人都可以在此体验到他们的爱好所带来的快乐的平台。通过遵守本行为准则中所规定的简单规则，可以确保每个人都能学习并且结交来自世界各地的新朋友。在此，欢迎我们的各位新会员，也希望大家可以享受这个平台所带来的乐趣。
> > 建议如上修改
> 
> “...的平台，最重要的是...”中将逗号改为句号或分号如何 @LeoChen98

我觉得前后分句有明确的递进关系，而不是并列关系，用逗号比较合适，建议征求更多人的意见。

2022-04-24 12:56 UTC, CaptainYukinoshitaHachiman commented on COC_translate_full.md
> +后记 - VATSIM的主要目标是提供一个有教育意义，同时模拟真实飞行和管制环境，并且，最重要的是所有人都可以在此体验到他们的爱好所带来的快乐的平台。通过遵守本行为准则中所规定的简单规则，可以确保每个人都能学习并且结交来自世界各地的新朋友。在此，欢迎我们的各位新会员，也希望大家可以享受这个平台所带来的乐趣。
> 我觉得前后分句有明确的递进关系，而不是并列关系，用逗号比较合适，建议征求更多人的意见。

问题是“VATSIM的主要目标是提供一个有教育意义，同时模拟真实飞行和管制环境的平台，最重要的是，我们希望所有人都可以在这里体验到爱好所带来的的快乐。”其实已经是两句话了

2022-04-24 13:14 UTC, LeoChen98 commented on COC_translate_full.md
> +后记 - VATSIM的主要目标是提供一个有教育意义，同时模拟真实飞行和管制环境，并且，最重要的是所有人都可以在此体验到他们的爱好所带来的快乐的平台。通过遵守本行为准则中所规定的简单规则，可以确保每个人都能学习并且结交来自世界各地的新朋友。在此，欢迎我们的各位新会员，也希望大家可以享受这个平台所带来的乐趣。
> > 我觉得前后分句有明确的递进关系，而不是并列关系，用逗号比较合适，建议征求更多人的意见。
> 
> 问题是“VATSIM的主要目标是提供一个有教育意义，同时模拟真实飞行和管制环境的平台，最重要的是，我们希望所有人都可以在这里体验到爱好所带来的的快乐。”其实已经是两句话了

也对，那就改成句号吧

2022-04-24 13:36 UTC, henrylzy commented on COC_translate_full.md
> +后记 - VATSIM的主要目标是提供一个有教育意义，同时模拟真实飞行和管制环境，以及一个所有人都可以在此体验到他们的爱好所带来的快乐的平台。通过遵守本行为准则中所规定的简单规则，可以确保每个人都能学习并且结交来自世界各地的新朋友。在此，欢迎我们的各位新会员，也希望大家可以享受这个平台所带来的乐趣。
可

2022-04-24 14:44 UTC, LeoChen98 commented on COC_translate_full.md
> +后记 - VATSIM的主要目标是提供一个有教育意义，同时模拟真实飞行和管制环境，并且，最重要的是所有人都可以在此体验到他们的爱好所带来的快乐的平台。通过遵守本行为准则中所规定的简单规则，可以确保每个人都能学习并且结交来自世界各地的新朋友。在此，欢迎我们的各位新会员，也希望大家可以享受这个平台所带来的乐趣。
```suggestion
后记 - VATSIM的主要目标是提供一个有教育意义，同时模拟真实飞行和管制环境的平台。最重要的是，我们希望所有人都可以在这里体验到爱好所带来的的快乐。通过遵守本行为准则中所规定的简单规则，可以确保每个人都能学习并且结交来自世界各地的新朋友。在此，欢迎我们的各位新会员，也希望大家可以享受这个平台所带来的乐趣。
```

2022-04-24 16:09 UTC, henrylzy commented on COC_translate_full.md
> +B5 - 飞行员在无管制空域内飞行时应当时刻守听122.800MHz或其他被指定为UNICOM的频率，直到其进入管制空域内。飞行员应当在指定的UNICOM频率中报告其意图以避免冲突，同时方便其他飞行员。
> > > > 这句话我一直觉得不太通顺，改成当其他飞行员有可能从中受益时稍好一些，但是还是有些奇怪
> > > 
> > > 
> > > 主要是按照现在的译法含义应该与原文有出入吧？ @henrylzy
> > 
> > 
> > 但是原文的意思没有当，而是这个行为可能会让其他人受益
> 
> @henrylzy where在这里应该是when的意思吧，还是我理解错了？

这个where指代在unicom声明意图这一行为，可以理解为从或者由

2022-04-24 16:13 UTC, henrylzy commented on COC_translate_full.md
> +C5 - 管制席位遵循’先到先得‘原则。经所属分部批准后，相关地区可以引入席位预定机制，允许管制员预约或计划于某一特定的（合理）时间段内在其指定席位提供管制服务。此外，当一位管制员与服务器的连接由于网络或其他因素而被中断，并在合理的时间范围内重新登陆时，另一名管制员已经登录了相同席位的情况下，后者应当将此席位归还至前者。
当前版本是first draft，暂不考虑排版以及外链，仅针对内容的通顺及合理性做修改

2022-04-24 16:37 UTC, LeoChen98 approved these changes
未发现其他需要修改处，同意合并到主分支，并建议继续优化排版。

2022-04-25 02:23 UTC, websterzh requested changes
有少量瑕疵，但是总体问题不大

2022-04-25 02:23 UTC, websterzh commented on COC_translate_full.md
> +A17 - 会员不得重现或组织任何有关真实世界中发生过的灾难、悲剧、或其他类似事件（尤其是那些最终导致了人员伤亡的事件）的飞行活动。此外，也禁止使用被VATSIM限制的呼号。(此处查看被限制呼号的列表)
括号中内容应为「参见受限呼号列表」并且应该带上链接？

2022-04-25 02:23 UTC, websterzh commented on COC_translate_full.md
> +VATSIM不希望对其会员进行持续性的监管。为此，当会员之间在连线过程中发生了冲突或摩擦时，如果各方当事人无法在当下快速处理，或者这些冲突或摩擦会导致其他会员无法正常的使用或享受这个平台时，当事人应当寻求在线的监察员或行政人员的帮助。
第一句：「VATSIM不会对其会员进行持续的监管。」

2022-04-25 02:23 UTC, websterzh commented on COC_translate_full.md
> +B3(b) - 当飞行员在飞行中遇到必须要离开电脑前的情况，我们鼓励飞行员断开与VATSIM的连接。即便本守则有与之相悖的规定，无人看管的飞行员连接最多不可以超过30分钟。
「鼓励」 -> 「建议」

2022-04-25 02:23 UTC, websterzh commented on COC_translate_full.md
> +B4 - 除被管制员要求外，飞行员应当在其飞机运动的过程中启用其应答机的C模式。模拟无应答机功能的飞行活动需要经过管制员批同意后方可进行。
「批同意」 -> 「同意」

2022-04-25 02:23 UTC, websterzh commented on COC_translate_full.md
> +C2 - 管制员应当遵守地方性的规则以及程序。选择在其所属或所被分配的地区/分部/分支机构以外的地区提供管制服务的管制员，必须遵守该地区的地方性规则及程序，并且需要根据当地要求，申请并取得“客座管制员”的身份。“客座管制员”的身份受到Transfer and Visiting Controllers Policy (https://www.vatsim.net/documents/transf
链接没贴全

2022-04-25 06:24 UTC, henrylzy commented on COC_translate_full.md
> +B2 - 除非管制员明确同意以外，飞行员不得在连线过程中将其模拟器暂停。当管制员要求时，飞行员应当立刻终止其模拟器的暂停状态。
我是瞎子。前半句说了有管制区域以外禁止暂停，管制区域内需要管制员同意。所以保持原翻译。

2022-04-25 12:46 UTC, henrylzy commented on COC_translate_full.md
> +VATSIM不希望对其会员进行持续性的监管。为此，当会员之间在连线过程中发生了冲突或摩擦时，如果各方当事人无法在当下快速处理，或者这些冲突或摩擦会导致其他会员无法正常的使用或享受这个平台时，当事人应当寻求在线的监察员或行政人员的帮助。
翻译成不会的话与原文意思相悖了，毕竟原文说的是不喜欢这样做

2022-04-25 16:40 UTC, websterzh approved these changes

2022-04-25 16:40 UTC, merged