Create bigflow_event.md
websterzh/vatprc-wiki pull request #17
Opened 2022-04-24 07:59 UTC by paul891014

對於大流量活動的介紹

2022-04-24 16:03 UTC, websterzh requested changes

2022-04-24 16:03 UTC, websterzh commented on bigflow_event.md
> +### 地面部分
可以提及流控的三个位置和优先级机制：等待点等待、停机位暂停推出、放行暂停放行

2022-04-24 16:03 UTC, websterzh commented on bigflow_event.md
> +这类活动的流量控制一般在3到6分钟一架，其他内容于C.相同。
于 -> 与

2022-04-25 02:25 UTC, websterzh requested changes
9ccfa8b 这里的「由于」没必要改

2022-04-25 13:31 UTC, djnken approved these changes
除文略提及的于和与的问题，其余没有意见

2022-04-25 17:44 UTC, henrylzy commented on bigflow_event.md
> +南方1354，增/减马赫数到0.81
```suggestion
南方1354，马赫数0.81(点八幺)
```
调整用语

2022-04-25 17:45 UTC, henrylzy commented on bigflow_event.md
> +CSN1354, Increase/Reduce Mach speed 0.81 due to separation.
```suggestion
CSN1354, Increase/Reduce Mach number 0.81 due to separation.
```
调整用语

2022-04-25 17:46 UTC, henrylzy commented on bigflow_event.md
> +南方1354，增/减表数到250节
```suggestion
南方1354，表速（调）250
```
调整用语

2022-04-25 17:47 UTC, henrylzy commented on bigflow_event.md
> +南方1354，保持180节到本场8海里，160节到6海里
```suggestion
南方1354，保持表速180到本场8海里，160到6海里
```
调整用语

2022-04-25 17:47 UTC, henrylzy commented on bigflow_event.md
> +南方1354,保持180节直到五边/航向道
```suggestion
南方1354,保持表速180直到五边/航向道
```
调整用语

2022-04-25 17:47 UTC, henrylzy commented on bigflow_event.md
> +南方1354，保持表速260或以上/以下
```suggestion
南方1354，表速260或以上/以下
```
调整用语

2022-04-25 17:51 UTC, henrylzy commented on bigflow_event.md
> +CSN1354,Maintain speed 260kt or greater/greater than 260kt
```suggestion
CSN1354, maintain speed 260kt or greater/less OR CSN1354, speed greater/less than 260kt
```
调整用语

2022-04-25 17:54 UTC, henrylzy commented on bigflow_event.md
> +(or greater 表以上/greater than表以下，当然管制员可能使用above/below来代表相同意思)
```suggestion
(260 or greater 表示大于等于260，greater than 260表示大于260。260 or less表示小于等于260，260 or less表示小于260，当然管制员可能使用above/below来代表相同意思)
```
修改注释

2022-04-25 17:55 UTC, henrylzy commented on bigflow_event.md
> +南方1354，取消速度限制(大表速)
```suggestion
南方1354，取消速度限制
```
速度限制可能是要求大速度或者小速度，所以不等同于大表速

2022-04-25 17:57 UTC, henrylzy commented on bigflow_event.md
> +神鹿629：无法执行指令，我们能最快/最慢1022分通过泽当
```suggestion
神鹿629：无法执行指令，我们能最早/最晚1022分通过泽当
```
调整用语

2022-04-25 17:58 UTC, henrylzy commented on bigflow_event.md
> +DKH1245, Direct AVBOX,Resume own nevigation
```suggestion
DKH1245, Direct AVBOX, Resume own navigation
```
修改错白字

2022-04-25 17:58 UTC, henrylzy commented on bigflow_event.md
> +DKH1245,Turn right heading 020,Clear ILS 35L approach,Report Localizer estabulished
```suggestion
DKH1245,Turn right heading 020,Clear ILS 35L approach, Report Localizer established
```
修改错白字

2022-04-25 17:59 UTC, henrylzy commented on bigflow_event.md
> +DKH1245,Right turn direct PD073,Clear ILS 35L approach,Report Localizer estabulished
```suggestion
DKH1245,Right turn direct PD073,Clear ILS 35L approach, Report Localizer established
```
修改错白字

2022-04-25 18:01 UTC, henrylzy commented on bigflow_event.md
> +CES519, make a left/right orbit at present location.
```suggestion
CES519, make a left/right orbit at present position.
```
position可能更合适一点

2022-04-26 06:35 UTC, AkiChen891 commented on bigflow_event.md
> ++ 尽早申请放行，尤其是大流量活动的放行席会随著时间的流逝而有越来越多的机组出现，请勿为了卡航班时段或者是等待活动正式开始才要放行许可。
著->着

2022-04-26 06:35 UTC, AkiChen891 commented on bigflow_event.md
> ++ 请勿在机位上开启引擎，这样会让你的油量在进场阶段处于低油量状态
请勿过早的启动双发引擎，过多的非必要油耗可能会让航空器在进场阶段处于低油量状态。

2022-04-26 06:35 UTC, AkiChen891 commented on bigflow_event.md
> +除了上面A.的情况外由于有没预订航班，所以离场时间取决于当下活动是否有空出的时间带，等待时间可能从1小时到数小时不等。
（没看懂这句话）建议改成：在没有预订航班时刻时，离场时间取决于活动时段是否有空出的时间带可用于非预订机组离场。由于活动需要优先保障有预订的机组，未预订时刻的机组可能会被要求进行等待，等待时间可能从1小时到数小时不等。

2022-04-26 08:41 UTC, LeoChen98 reviewed
除已指出问题外，未发现其他问题，但基于排版美观性提出以下建议

1. 建议使用markdown自带列表工具排序
2. 建议检查英文语句中标点符号附近空格情况和单词首字母大写情况。

2022-04-26 08:41 UTC, LeoChen98 commented on bigflow_event.md
> ++ 6.保持一颗愉悦的心：被要求等待的不会只有你一人，放宽心享受飞行吧
```suggestion
1. 避免离开电脑前超过10分钟：即使COC允许机组在管制的同意下能够最多离开30分钟
2. 避免使用倍速：除非管制允许的情况下，否则根据COC禁止开启倍速功能，另外不提倡在活动中向管制员申请开启倍速功能
3. 避免关闭或手动修改天气：请使用真实天气进行飞行，除非你的连飞软件不具备该功能
4. 确保网路、语音以及设备处于良好连接的状态：频繁的断线以及麦克风问题可能会造成管制员以及其他机组的困扰
5. 拥有最新的导航数据以及航图：请确保在活动前拥有最新一期的导航数据以及航图，在能力范围内请确保使用最新的机场地景进行飞行
6. 保持一颗愉悦的心：被要求等待的不会只有你一人，放宽心享受飞行吧
```
建议使用markdown自带列表工具排序

2022-04-26 08:41 UTC, LeoChen98 commented on bigflow_event.md
> ++ 3.活动机场的其中一边管制方式为非雷达管制或特殊机场(例如：成都-拉萨)。
```suggestion
一般来说，大流量活动会大致出现三个特征：
1. 在活动页面中出现航班预定的页面链接(例如：Cross the pond、丝路)。
2. 两个或多个主要机场对飞(例如：京沪、墨尔本-悉尼等等)。
3. 活动机场的其中一边管制方式为非雷达管制或特殊机场(例如：成都-拉萨)。
```

建议使用markdown自带列表工具排序

2022-04-26 08:41 UTC, LeoChen98 commented on bigflow_event.md
> ++ 3.等待点流控
```suggestion
1. 放行流控
2. 推开流控
3. 等待点流控
```

建议使用markdown自带列表工具排序

2022-04-26 08:41 UTC, LeoChen98 commented on bigflow_event.md
> ++ 4.等待与盘旋
```suggestion
1. 速度控制
2. 过特定点时间
3. 雷达引导
4. 等待与盘旋
```

建议使用markdown自带列表工具排序

2022-04-26 09:06 UTC, paul891014 commented on bigflow_event.md
> ++ 尽早申请放行，尤其是大流量活动的放行席会随著时间的流逝而有越来越多的机组出现，请勿为了卡航班时段或者是等待活动正式开始才要放行许可。
已經改成等待

2022-04-26 10:32 UTC, LeoChen98 approved these changes
未见其他问题，同意合并。

2022-04-26 15:39 UTC, merged