Navigation
websterzh/vatprc-wiki pull request #18
Opened 2022-04-24 09:09 UTC by djnken

#9 
包含pbn进离场和传统进离场。

2022-04-24 15:37 UTC, websterzh commented on PBN进离场.md
> +# ***PBN进离场***
不需要斜体

2022-04-24 15:38 UTC, websterzh commented on PBN进离场.md
> +# ***PBN进离场***
不需要斜体

2022-04-24 15:45 UTC, websterzh requested changes

2022-04-24 15:45 UTC, websterzh commented on PBN进离场.md
> +一般而言，每个离场程序都绑定了某一条跑道，因此只需要根据计划用于离场的跑道选择相应的离场程序即可。例如计划使用01号跑道离场，离场点为MUGLO，由图中可知，使用的离场程序为MUGLO-9YD（在机模上因为编码的原因可能会被缩写为MUG9YD）。
这里的这些航点和程序，可以在MD中有反引号 \` 框起来变成代码格式：如`MUGLO`, `MUGLO-9YD`。下文同理

2022-04-24 15:45 UTC, websterzh commented on 传统进离场.md
> +对于基于一个VOR设计的传统离场，一般会有以下几种行为：过台、二次过台、切该台的某某径向线、切该台的某某径向线并测距某海里。
此处使用列表。
+ 第一项
+ 第二项
+ 第三项

2022-04-24 15:45 UTC, websterzh commented on 传统进离场.md
> +# ***传统进离场***
可不用斜体

2022-04-24 15:45 UTC, websterzh commented on 传统进离场.md
> +对于基于一个VOR设计的传统离场，一般会有以下几种行为：过台、二次过台、切该台的某某径向线、切该台的某某径向线并测距某海里。
可能需要定义径向线、过台等名词

2022-04-24 15:45 UTC, websterzh commented on 传统进离场.md
> +NDB进近的进场程序部分通常与其他方式一致，因此不再重复，从起始进近开始介绍。
可加入连接提及（引用）一下另一个文章

2022-04-25 06:21 UTC, djnken commented on 传统进离场.md
> +NDB进近的进场程序部分通常与其他方式一致，因此不再重复，从起始进近开始介绍。
正好是上文，无需引用

2022-04-25 10:15 UTC, websterzh approved these changes

2022-04-25 12:21 UTC, AkiChen891 approved these changes
RNP定义

2022-04-25 12:21 UTC, AkiChen891 commented on PBN进离场.md
> +## RNP进近
RNP(GNSS)或RNP(AR)进近

2022-04-25 12:21 UTC, AkiChen891 commented on PBN进离场.md
> +当飞机接近决断高度时，`FINAL APP`模式将脱开，机组接管继续着陆。
机组接管自动驾驶，手动进行落地。

2022-04-25 13:39 UTC, merged