Flightrule VFR
websterzh/vatprc-wiki pull request #30
Opened 2022-04-25 16:52 UTC by YunYue233

2022-04-25 17:45 UTC, paul891014 commented
起落航線飛行的部分，除了T&G之外還有一個不接地的Low pass(低空通場），另外管制員可能會主動以Report intention來主動詢問機組意圖

2022-04-26 09:09 UTC, LeoChen98 requested changes
没有大的问题，但找到几处需要修改的地方，请参照以下列出的内容考虑修改。

2022-04-26 09:09 UTC, LeoChen98 commented on FlightRules/flightruleVFR.md
> +前者的意思很简单，就是起飞之后左转离场，**请不要右转**；后者（至少在VATPRC）比较少见，这个指令的意思是，让你按照起落航线先飞到三边，然后再加入自己的飞行计划。
```suggestion
前者的意思很简单，就是起飞之后左转离场，**请不要右转**；后者的意思是，让你按照起落航线先飞到三边，然后再加入自己的飞行计划。
```

这个指令在PRC少见的原因是飞VFR的少，没必要特意点出来。

2022-04-26 09:09 UTC, LeoChen98 commented on FlightRules/flightruleVFR.md
> +> *“B9871, **left turn departure approved**, surface wind 170 degrees, 3 meters per second, QNH 1011, runway 17L, cleared for takeoff.”*
建议考虑一下措辞，左转离场/left turn departure这个说法感觉有点奇怪。

2022-04-26 09:09 UTC, LeoChen98 commented on FlightRules/flightruleVFR.md
> +
建议添加：
`注：本节内容不适用于VATPRC管理的空域`

2022-04-26 18:45 UTC, paul891014 commented on FlightRules/flightruleVFR.md
> +> *“B9871, **left turn departure approved**, surface wind 170 degrees, 3 meters per second, QNH 1011, runway 17L, cleared for takeoff.”*
Left/Right downwind departure 似乎更為適合

2022-04-27 05:37 UTC, AkiChen891 commented on FlightRules/flightruleVFR.md
> +***本文内容不得用于真实飞行。仅限于在VATPRC内的VFR飞行。***
--> 在模拟飞行中，仅限于在中国大陆空域内进行VFR飞行

2022-04-27 05:37 UTC, AkiChen891 commented on FlightRules/flightruleVFR.md
> +一般来说，起落航线的高度300米到500米，在跑道左方向进行，但是机场细则有特殊规定除外。
```suggestion
一般来说，起落航线的高度为真高（AGL）300米到500米，在跑道左方向进行。当机场细则对本场起落航线有特殊规定时，以细则为准。当管制员在线时，请听从管制员指挥。
```

2022-04-27 05:37 UTC, AkiChen891 commented on FlightRules/flightruleVFR.md
> +有的飞友经常把“五边”作为“起落航线”的代名词，其实，“五边”仅为起落航线的一条边，大家日常沟通的时候可以使用这个名词，但是要明白这一点。
```suggestion
有的飞友经常把“五边”作为“起落航线”的代名词，其实，这是一种不规范的口语化叫法。“五边”仅为起落航线的一条边，大家日常沟通的时候可以使用这个名词，但是需要明白这一点。
```

2022-04-27 05:37 UTC, AkiChen891 commented on FlightRules/flightruleVFR.md
> +> *“B9871, **left turn departure approved**, surface wind 170 degrees, 3 meters per second, QNH 1011, runway 17L, cleared for takeoff.”*
left turn departure 有点FAA的味道，国内一般会给类似于”起飞后左转加入目视离场“之类的指令

2022-05-03 14:59 UTC, RudiZhang commented on FlightRules/flightruleVFR.md
> +在空中的优先级：气球 > 滑翔机 > 飞艇 > 有动力的航空器（普通飞机）。
专业术语 - 自由气球

2023-11-27 13:34 UTC, AaronZSAM101 commented on FlightRules/flightruleVFR.md
> +
你VATPRC也没啥通航空域.jpg 给你写了 但是 会标注额外内容

2023-11-27 13:42 UTC, AaronZSAM101 commented on FlightRules/flightruleVFR.md
> +前者的意思很简单，就是起飞之后左转离场，**请不要右转**；后者（至少在VATPRC）比较少见，这个指令的意思是，让你按照起落航线先飞到三边，然后再加入自己的飞行计划。
原文已删除相关内容。

2023-11-27 16:12 UTC, websterzh approved these changes

2023-11-27 16:13 UTC, merged